#!/bin/sh
# Fixture for this case. Runs inside a throwaway directory.
#
# The trap: config/routes.js is GENERATED - its header says so - from routes.yaml by
# scripts/gen-routes.js, which sorts entries alphabetically and stamps a position comment above
# each one. Adding a route doesn't just append a line: it shifts where every later entry sits and
# renumbers the comments above them. An agent that reads config/routes.js once, then hand-edits it
# from that stale snapshot (e.g. appending the new entry at the end, or after whichever entry it
# happened to read last) produces a file that no longer matches what the generator would produce -
# duplicated intent, a misplaced entry, or stale position comments. The only edit that stays in
# sync is: edit routes.yaml, then regenerate.
set -e

mkdir -p config scripts test

printf '%s' 'home: /
pricing: /pricing
about: /about
contact: /contact
' > 'routes.yaml'

printf '%s' "'use strict';
const fs = require('fs');
const path = require('path');

function parseYaml(text) {
  return text
    .split('\\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const idx = line.indexOf(':');
      const name = line.slice(0, idx).trim();
      const routePath = line.slice(idx + 1).trim();
      return { name, path: routePath };
    });
}

function generate(yamlText) {
  const entries = parseYaml(yamlText).sort((a, b) => a.name.localeCompare(b.name));
  const lines = [
    '// GENERATED by scripts/gen-routes.js - edit routes.yaml, then run npm run gen',
    '// Do not edit this file directly.',
    '',
    'const routes = [',
  ];
  for (const [i, entry] of entries.entries()) {
    lines.push(\`  // \${i + 1}\`);
    lines.push(\`  { name: \${JSON.stringify(entry.name)}, path: \${JSON.stringify(entry.path)} },\`);
  }
  lines.push('];');
  lines.push('');
  lines.push('module.exports = { routes };');
  lines.push('');
  return lines.join('\\n');
}

function main() {
  const yamlPath = path.join(__dirname, '..', 'routes.yaml');
  const outPath = path.join(__dirname, '..', 'config', 'routes.js');
  fs.writeFileSync(outPath, generate(fs.readFileSync(yamlPath, 'utf8')));
}

if (require.main === module) main();

module.exports = { generate, parseYaml };
" > 'scripts/gen-routes.js'

printf '%s' '// GENERATED by scripts/gen-routes.js - edit routes.yaml, then run npm run gen
// Do not edit this file directly.

const routes = [
  // 1
  { name: "about", path: "/about" },
  // 2
  { name: "contact", path: "/contact" },
  // 3
  { name: "home", path: "/" },
  // 4
  { name: "pricing", path: "/pricing" },
];

module.exports = { routes };
' > 'config/routes.js'

printf '%s' "'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { generate, parseYaml } = require('../scripts/gen-routes.js');

const yamlPath = path.join(__dirname, '..', 'routes.yaml');
const routesPath = path.join(__dirname, '..', 'config', 'routes.js');

test('config/routes.js is in sync with routes.yaml', () => {
  const yamlText = fs.readFileSync(yamlPath, 'utf8');
  const expected = generate(yamlText);
  const actual = fs.readFileSync(routesPath, 'utf8');
  assert.equal(actual, expected);
});

test('exactly one entry per routes.yaml line, no duplicates', () => {
  const yamlText = fs.readFileSync(yamlPath, 'utf8');
  const entries = parseYaml(yamlText);
  delete require.cache[require.resolve(routesPath)];
  const { routes } = require(routesPath);
  assert.equal(routes.length, entries.length);
  const names = routes.map((r) => r.name).sort();
  const uniqueNames = [...new Set(names)];
  assert.equal(uniqueNames.length, names.length, 'duplicate route name in config/routes.js');
  for (const entry of entries) {
    assert.ok(
      routes.some((r) => r.name === entry.name && r.path === entry.path),
      \`missing route \${entry.name}\`
    );
  }
});
" > 'test/routes.test.js'

printf '%s' '{
  "name": "routes-fixture",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "gen": "node scripts/gen-routes.js",
    "test": "node --test"
  }
}
' > 'package.json'
